# Generated by Django 5.1.2 on 2024-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(default='DEFAULT_CODE', max_length=20, unique=True)),
                ('temp_stock_code', models.CharField(default='TEMP_CODE', max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=100)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
