# Generated by Django 5.1.2 on 2024-11-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='temp_stock_code',
        ),
    ]
