# Generated by Django 5.1.2 on 2024-11-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_stock_options_alter_stock_stock_code_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
