# Generated by Django 5.1.2 on 2024-11-02 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_alter_stock_options_alter_stock_stock_code_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
