# Generated by Django 5.1.2 on 2024-11-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12),
        ),
    ]
